Object.defineProperty(exports, "__esModule", { value: true });
var LOADER_VISIBLITY = (exports.LOADER_VISIBLITY = "LOADER_VISIBLITY");
var STOP_LOADER = (exports.STOP_LOADER = "STOP_LOADER");
var GPS_LOCATION = (exports.GPS_LOCATION = "GPS_LOCATION");
var SELECTED_LOCATION = (exports.SELECTED_LOCATION = "SELECTED_LOCATION");
var LOCATION_DISABLED = (exports.LOCATION_DISABLED = "LOCATION_DISABLED");
var DISTANCE_LOCATION = (exports.DISTANCE_LOCATION = "DISTANCE_LOCATION");
var SET_ADDRESS = (exports.SET_ADDRESS = "SET_ADDRESS");
var GOBACK = (exports.GOBACK = "GOBACK");
var ResetNavigator = (exports.ResetNavigator = "ResetNavigator");
var ResetDashboard = (exports.ResetDashboard = "ResetCustomNavigator");
var GOTO = (exports.GOTO = "GOTO");
var NEW_INSTALL = (exports.NEW_INSTALL = "NEW_INSTALL");
var DEVICE_TOKEN = (exports.DEVICE_TOKEN = "DEVICE_TOKEN");
var LOGOUT = (exports.LOGOUT = "LOGOUT");
var USER_PROFILE = (exports.USER_PROFILE = "USER_PROFILE");
var UPDATE_PROFILE = (exports.UPDATE_PROFILE = "UPDATE_PROFILE");
var PENDING_PROFILE_UPDATE = (exports.PENDING_PROFILE_UPDATE =
  "PENDING_PROFILE_UPDATE");
var SET_BOOKING_DATA = (exports.SET_BOOKING_DATA = "SET_BOOKING_DATA");
var BOOKING_DATA_IS_SOS = (exports.BOOKING_DATA_IS_SOS = "BOOKING_DATA_IS_SOS");
var IS_SOS_OPENED_AGAIN = (exports.IS_SOS_OPENED_AGAIN = "IS_SOS_OPENED_AGAIN");
